from __future__ import annotations

import re
import unicodedata

from bs4 import BeautifulSoup
from markdownify import markdownify as md

from models import Article

NOISE_SELECTORS = [
    "script",
    "style",
    "noscript",
    ".article-votes",
    ".article-more-questions",
    ".article-return-to-top",
    ".share",
    ".related-articles",
    ".recent-articles",
    ".breadcrumbs",
    ".pagination",
]


def slugify(value: str, max_length: int = 90) -> str:
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value[:max_length].strip("-") or "article"


def clean_html(html: str) -> str:
    soup = BeautifulSoup(html or "", "html.parser")

    for selector in NOISE_SELECTORS:
        for tag in soup.select(selector):
            tag.decompose()

    # Remove empty anchors generated by UI fragments.
    for tag in soup.find_all(["a"]):
        if not tag.get_text(strip=True) and not tag.find("img"):
            tag.decompose()

    # Normalize image alt text.
    for img in soup.find_all("img"):
        alt = img.get("alt") or img.get("title") or "image"
        img["alt"] = alt.strip()

    return str(soup)


def html_to_markdown(html: str) -> str:
    cleaned = clean_html(html)

    markdown = md(
        cleaned,
        heading_style="ATX",
        bullets="-",
        code_language="",
        strip=["span"],
    )

    markdown = normalize_markdown(markdown)
    return markdown


def normalize_markdown(markdown: str) -> str:
    text = markdown.replace("\r\n", "\n").replace("\r", "\n")

    # Remove excessive blank lines.
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Remove Zendesk feedback fragments if they survive HTML cleanup.
    unwanted_lines = [
        "Was this article helpful?",
        "Have more questions?",
        "Submit a request",
        "Return to top",
    ]

    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped in unwanted_lines:
            continue
        lines.append(line.rstrip())

    return "\n".join(lines).strip() + "\n"


def article_to_markdown(article: Article) -> str:
    body_md = html_to_markdown(article.body_html)

    title = article.title.strip()
    frontmatter = f"""---
Article ID: {article.article_id}
Article URL: {article.html_url}
Title: {title}
Updated At: {article.updated_at}
---

# {title}

"""

    # Avoid duplicate H1 if article body already starts with same title.
    body_md = re.sub(
        rf"^#\s+{re.escape(title)}\s*\n+", "", body_md, flags=re.IGNORECASE
    )

    return frontmatter + body_md
